# Blog settings
permalink: /blog/:title


# My variables
name: Micha Daniel 路 software developer 路 Krak贸w
description: Hello. I'm Micha Daniel, an application developer from Krak贸w, Poland. I work on mobile and desktop apps, love free software, and I'm interested in security and privacy. This is my personal website, blog, online curriculum vitae, and applications portfolio.
author:
  name: Micha Daniel
  location: Krak贸w, Poland 
  url: https://osm.org/go/0L0Npn_U--?m=
copyright: Copyright Micha Daniel 2019+

promo: /assets/img/site-promo.png


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "CNAME", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Site
url: https://morningbird.eu
website: morningbird.eu
sources: https://github.com/michaldaniel/morningbird.eu
